[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pubflow"
version = "0.1.0"
description = "ESGF publication workflow manager"
requires-python = ">=3.10"

dependencies = [
    "duckdb",
    "pyyaml",
    "typer",
    "requests",
    "tqdm",
]

[project.scripts]
pubflow = "pubflow.cli:app"

[tool.setuptools]
packages = [
    "pubflow",
    "workflow",
]