campaigns:

  tipmip-cnrm:

    project: CMIP6Plus
    activity: TIPMIP
    institution: CNRM-CERFACS

    mapfile_root: /modfs/esgf/topublish/CNRM-CERFACS/.mapfiles

    archive:
      enabled: true
      root: /mnt/scality/WCRP/CMIP6Plus/TIPMIP/CNRM-CERFACS
      depth: experiment_id

  tipmip-ubern:

    project: CMIP6Plus
    activity: TIPMIP
    institution: UBERN

    mapfile_root: /modfs/esgf/topublish/UBERN/.mapfiles



    archive:
      enabled: true
      root: /mnt/scality/WCRP/CMIP6Plus/TIPMIP/UBERN
      depth: experiment_id


  tipmip-uib:

    project: CMIP6Plus
    activity: TIPMIP
    institution: UiB

    mapfile_root: /modfs/esgf/topublish/UiB/.mapfiles


    archive:
      enabled: true
      root: /mnt/scality/WCRP/CMIP6Plus/TIPMIP/UiB
      depth: experiment_id

  cmip6-ipsl-cm6a-lr-picontrol:
    project: CMIP6
    activity: CMIP
    institution: IPSL
    mapfile_root: /mnt/tgcc/CMIP6/.mapfiles/CMIP/IPSL/IPSL-CM6A-LR/piControl
    archive:
      enabled: false

  cmip6-ipsl-cm6a-lr-1pctCO2:
    project: CMIP6
    activity: CMIP
    institution: IPSL
    mapfile_root: /mnt/tgcc/CMIP6/.mapfiles/CMIP/IPSL/IPSL-CM6A-LR/1pctCO2
    archive:
      enabled: false