publisher:
  executable: esgpublish
  arguments:
    - --no-xarray
  batch:
    size: 100
  execution:
    dry_run: false
  logging:
    directory: logs
  stac_items:
    directory: stac-items
  retry:
    enabled: true
    max_attempts: 3
  mapfile_path_mappings:
    - from: /ccc/work/cont003/cmip6/cmip6
      to: /mnt/tgcc/
  esg:
    config:
      active: EAST-int
      profiles:
        EAST-int:
          path: ~/.esg/esg.yaml.EASTINT
        WEST-int:
          path: ~/.esg/esg.yaml.WESTINT
        EAST-prod:
          path: ~/.esg/esg.yaml.EAST
        WEST-prod:
          path: ~/.esg/esg.yaml.WEST
