publisher:

  executable: esgpublish

  arguments: [ ]

  batch:
    size: 50

  execution:
    dry_run: false

  logging:
    directory: /home/esguser/esgf-publisher-workflow/logs

  retry:
    enabled: true
    max_attempts: 3